events {
    worker_connections 1024;
}

http{
    server{
        listen 80;

        location /gateway_health {
            return 200 "gateway_health OK!";
        }

        location / {
            return 404;
        }
    }
}